[tool.poetry]
name = "test-sc"
version = "0.1.0"
description = ""
authors = ["Florian Rodriguez <florian.rodriguez@sharingcloud.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
fastapi = {extras = ["standard"], version = "^0.115.5"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
